# Generated by Django 4.0.5 on 2022-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='메롱', max_length=50, null=True)),
                ('view_auth', models.IntegerField(blank=True, default=0, null=True)),
                ('color', models.CharField(blank=True, default='#808080', max_length=20, null=True)),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
